#Measures_VersionForPaper.o: Measures_VersionForPaper.cpp GraphNN_VersionForPaper.h
	g++ -c -O2   Measures_VersionForPaper.cpp
#CommonMath_VersionForPaper.o:	 CommonMath_VersionForPaper.cpp CommonMath_VersionForPaper.h
	g++ -c -O2   CommonMath_VersionForPaper.cpp
#Simplex_VersionForPaper.o:Simplex_VersionForPaper.cpp GraphNN_VersionForPaper.h
	g++ -c -O2   Simplex_VersionForPaper.cpp
#AddEdges_VersionForPaper.o:	 AddEdges_VersionForPaper.cpp GraphNN_VersionForPaper.h
#	g++ -c -O2   AddEdges_VersionForPaper.cpp
#AddEdgesVertices_VersionForPaper.o:	 AddEdgesVertices_VersionForPaper.cpp GraphNN_VersionForPaper.h
	g++ -c -O2   AddEdgesVertices_VersionForPaper.cpp
#Printout_VersionForPaper.o:	 Printout_VersionForPaper.cpp GraphNN_VersionForPaper.h
	g++ -c -O2   Printout_VersionForPaper.cpp
#FileIO_VersionForPaper.o:	 FileIO_VersionForPaper.cpp FileIO_VersionForPaper.h
	g++ -c -O2  FileIO_VersionForPaper.cpp
#RemoveVectors_VersionForPaper.o:	 RemoveVectors_VersionForPaper.cpp GraphNN_VersionForPaper.h
	g++ -c -O2  RemoveVectors_VersionForPaper.cpp
#SpanningTree_VersionForPaper.o:	 SpanningTree_VersionForPaper.cpp GraphNN_VersionForPaper.h 
	g++ -c -O2   SpanningTree_VersionForPaper.cpp
#CompareBy_VersionForPaper.o:	 CompareBy_VersionForPaper.cpp GraphNN_VersionForPaper.h 
	g++ -c -O2   CompareBy_VersionForPaper.cpp
#SetComponentsAndLabelExteriorPaths.o:	SetComponentsAndLabelExteriorPaths.cpp GraphNN_VersionForPaper.h
	g++ -c -O2  SetComponentsAndLabelExteriorPaths.cpp
#Simplex_VersionForPaper:	Simplex_VersionForPaper.o FileIO_VersionForPaper.o AddEdgesVertices_VersionForPaper.o RemoveVectors_VersionForPaper.o CompareBy_VersionForPaper.o Measures_VersionForPaper.o CommonMath_VersionForPaper.o  Printout_VersionForPaper.o   SpanningTree_VersionForPaper.o SetComponentsAndLabelExteriorPaths.o
	g++ -O2 -o Simplex_VersionForPaper Simplex_VersionForPaper.o FileIO_VersionForPaper.o AddEdgesVertices_VersionForPaper.o RemoveVectors_VersionForPaper.o CompareBy_VersionForPaper.o Measures_VersionForPaper.o CommonMath_VersionForPaper.o  Printout_VersionForPaper.o  SpanningTree_VersionForPaper.o SetComponentsAndLabelExteriorPaths.o 
